version: "2"

services:
  influxdb:
    image: "library/influxdb"
    networks:
    - shoutcast
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=shoutcast
      - INFLUXDB_USER=shoutcast      
      - INFLUXDB_USER_PASSWORD=1shoutcast!
  grafana:
    image: "grafana/grafana"
    environment:
    - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/
    ports:
    - "3000:3000"
    networks:
    - shoutcast
    volumes:
    - grafana:/var/lib/grafana
  monitor:
    image: "shoutcast-monitor"
    networks:
    - shoutcast
    volumes:
    - /opt/monitor:/opt/monitor

networks:
  shoutcast:

volumes:
  influxdb:
  grafana:
